"use client";

import { motion } from "framer-motion";
import {
  Info,
  BookOpen,
  Github,
  ExternalLink,
  AlertTriangle,
} from "lucide-react";

const techStack = [
  { name: "Python", category: "Backend" },
  { name: "TensorFlow / Keras", category: "Deep Learning" },
  { name: "Scikit-learn", category: "ML Pipeline" },
  { name: "XGBoost", category: "Gradient Boosting" },
  { name: "SHAP", category: "Explainability" },
  { name: "Next.js / React", category: "Frontend" },
  { name: "Tailwind CSS", category: "Styling" },
  { name: "Recharts", category: "Visualization" },
  { name: "Framer Motion", category: "Animation" },
];

const references = [
  {
    title: "Cleveland Heart Disease Dataset",
    source: "UCI Machine Learning Repository",
    url: "https://archive.ics.uci.edu/ml/datasets/heart+disease",
  },
  {
    title: "MIT-BIH Arrhythmia Database",
    source: "PhysioNet",
    url: "https://physionet.org/content/mitdb/1.0.0/",
  },
  {
    title: "SHAP: SHapley Additive exPlanations",
    source: "Lundberg & Lee, NeurIPS 2017",
    url: "https://github.com/slundberg/shap",
  },
];

export default function AboutSection() {
  return (
    <section id="about" className="py-20 lg:py-28 bg-muted/30">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-12"
        >
          <span className="inline-flex items-center gap-2 rounded-full bg-secondary px-4 py-1.5 text-sm font-medium text-secondary-foreground mb-4">
            <Info className="h-3.5 w-3.5" />
            About the Project
          </span>
          <h2 className="text-3xl sm:text-4xl font-bold text-foreground text-balance">
            CardioML Research Project
          </h2>
          <p className="mt-3 mx-auto max-w-2xl text-muted-foreground leading-relaxed">
            An academic research project exploring hybrid machine learning
            approaches for explainable heart disease risk prediction.
          </p>
        </motion.div>

        <div className="grid lg:grid-cols-2 gap-8">
          {/* Disclaimer */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="rounded-2xl border-2 border-warning/30 bg-warning/5 p-6"
          >
            <div className="flex items-center gap-3 mb-4">
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-warning/10 text-warning">
                <AlertTriangle className="h-5 w-5" />
              </div>
              <h3 className="text-lg font-semibold text-foreground">
                Research Disclaimer
              </h3>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed">
              This is an academic research project and should not be used for
              actual medical diagnosis. The predictions generated by this tool
              are based on machine learning models trained on historical data and
              should not replace professional medical advice, diagnosis, or
              treatment. Always consult a qualified healthcare professional for
              any medical concerns.
            </p>
          </motion.div>

          {/* Tech Stack */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.1, duration: 0.6 }}
            className="rounded-2xl border border-border bg-card p-6"
          >
            <h3 className="text-lg font-semibold text-foreground mb-4">
              Technology Stack
            </h3>
            <div className="flex flex-wrap gap-2">
              {techStack.map((tech) => (
                <div
                  key={tech.name}
                  className="flex flex-col rounded-lg border border-border bg-muted/30 px-3 py-2"
                >
                  <span className="text-sm font-medium text-foreground">
                    {tech.name}
                  </span>
                  <span className="text-xs text-muted-foreground">
                    {tech.category}
                  </span>
                </div>
              ))}
            </div>
          </motion.div>

          {/* References */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.2, duration: 0.6 }}
            className="rounded-2xl border border-border bg-card p-6"
          >
            <div className="flex items-center gap-2 mb-4">
              <BookOpen className="h-5 w-5 text-primary" />
              <h3 className="text-lg font-semibold text-foreground">
                References
              </h3>
            </div>
            <div className="flex flex-col gap-3">
              {references.map((ref) => (
                <a
                  key={ref.title}
                  href={ref.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="group flex items-start justify-between gap-2 rounded-lg border border-border bg-muted/20 p-3 transition-colors hover:bg-muted/50 hover:border-primary/30"
                >
                  <div>
                    <p className="text-sm font-medium text-foreground group-hover:text-primary transition-colors">
                      {ref.title}
                    </p>
                    <p className="text-xs text-muted-foreground">
                      {ref.source}
                    </p>
                  </div>
                  <ExternalLink className="h-4 w-4 text-muted-foreground shrink-0 mt-0.5 group-hover:text-primary transition-colors" />
                </a>
              ))}
            </div>
          </motion.div>

          {/* Source Code */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.3, duration: 0.6 }}
            className="rounded-2xl border border-border bg-card p-6"
          >
            <div className="flex items-center gap-2 mb-4">
              <Github className="h-5 w-5 text-primary" />
              <h3 className="text-lg font-semibold text-foreground">
                Open Source
              </h3>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed mb-4">
              The full source code for CardioML is available on GitHub. The
              repository includes training scripts, model artifacts, evaluation
              pipelines, and this web application.
            </p>
            <a
              href="https://github.com/Aravind633/CardioML-Hybrid-XAI"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground transition-all hover:opacity-90 hover:scale-[1.02] active:scale-[0.98]"
            >
              <Github className="h-4 w-4" />
              View on GitHub
            </a>
          </motion.div>
        </div>
      </div>
    </section>
  );
}
